### PR TITLE
IO Optimizations and ObjectMember Key Support

### PR DESCRIPTION
**Pull request by ErikWitkowski**
Import/Export engines:

- Objects as serialization key - ComplexMembers like Objects now
supports SerializationKey attribute properly.
- RefElelement's keys values are now safely exported, like properties
values.
- The FindObjectFromRefenceElement method will find an element where all
keys matches, instead of the first element where at least one key member
match.
- Importer keeps a reference of all imported objects, instead of running
InTransaction queries to get the reference everytime - It supports
SerializationKeys objects scenarios.
- When exporting, it will no longer query the database for the
SerializationConfiguration object on every single record export, which
was unnecessary.

Graph Generation:

- If the property strategy is set to DoNotSerialize at model, it will no
longer be set as key.
- A graph for a related member will only be generated if the member
serialize strategy is set to object or value.
- It will no longer clear the second key avaliable, on function
ResetDefaultKeyWhenMultiple, because it makes no sense to remove a key
you have set with SerializationKeyAttribute.​

### CODE REVIEW

**Comment by ErikWitkowski** [comment]
I'm done with this for now, but the ObjectMember Key could use a EasyTest.. I suppose I could commit one in the future.

**Comment by apobekiaris** [comment]
I asked because i saw you close the request. Anyway, there is no need to
send requests at all, if you like you can personally mail the commits you
want me to cherry pick. As you probably know I avoid to code without
EasyTests, even the simplest test works really well and I many times amazed
on how many "unrelated" bugs are cought

On Fri, Sep 18, 2015 at 1:55 AM, ErikWitkowski <notifications@github.com>
wrote:

> I'm done with this for now, but the ObjectMember Key could use a
> EasyTest.. I suppose I could commit one in the future.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expand/eXpand/pull/98#issuecomment-141263169>.
>



-- 
Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by ErikWitkowski** [comment]
I understand. Good thing about this request is that basically all changed code is already covered by existent EasyTests. Anyway, one more XML test example for IO test would be good to make sure the scenario I wrote keep working on next versions.

**Comment by apobekiaris** [comment]
coverage is good however what the functionality supports remains hidden and
will be forgotten on the next refactor

On Fri, Sep 18, 2015 at 10:41 PM, ErikWitkowski <notifications@github.com>
wrote:

> I understand. Good thing about this request is that basically all changed
> code is already covered by existent EasyTests. Anyway, one more XML test
> example for IO test would be good to make sure the scenario I wrote keep
> working on next versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expand/eXpand/pull/98#issuecomment-141548847>.
>



-- 
Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by expand** [comment]
I use EasyTests to describe what an implementation does and not what it
doesn't and all possible fail scenarios.

On Sat, Sep 19, 2015 at 6:13 PM, Apostolis Bekiaris <
notifications@github.com> wrote:

> coverage is good however what the functionality supports remains hidden and
> will be forgotten on the next refactor
>
> On Fri, Sep 18, 2015 at 10:41 PM, ErikWitkowski <notifications@github.com>
> wrote:
>
> > I understand. Good thing about this request is that basically all changed
> > code is already covered by existent EasyTests. Anyway, one more XML test
> > example for IO test would be good to make sure the scenario I wrote keep
> > working on next versions.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/expand/eXpand/pull/98#issuecomment-141548847>.
> >
>
>
>
> --
> Apostolis Bekiaris
> Frameworks Technical Evangelist @ DevExpress
> Blog @ http://apobekiaris.blogspot.com
> Skype/twitter: tolisss
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/expand/eXpand/pull/98#issuecomment-141678837>.
>



-- 
Apostolis Bekiaris
Frameworks Technical Evangelist @ DevExpress
Blog @ http://apobekiaris.blogspot.com
Skype/twitter: tolisss

**Comment by ErikWitkowski** [comment]
K, I'll write an EasyTest to the supported functionality and I should be able to commit it within the next few days.

Date: Sat, 19 Sep 2015 08:19:05 -0700

**Comment by expand** [comment]
merged in 15.1.6.3

**Comment by expand** [comment]
I am sorry this does not compile please make sure that at least the IOTester related easytests pass. I will reopen the request

**Comment by ErikWitkowski** [comment]
Compile error fixed, and IOTester passed, including the new EasyTest.

**Comment by ErikWitkowski** [comment]
I can work on those conflicts tonight.

**Comment by ErikWitkowski** [comment]
Now it's conflict free and Win testes passsed, but I'm having a hard time trying to test on Web. I think when EasyTest expect the browser to open a file dialog, my IE 11 shows a popup instead..

**Comment by apobekiaris** [comment]
give me some time i will update u

**Comment by expand** [comment]
I am not sure why you get so many conficts my personal repo is not in total sync with the main and still do not have conlicts i merged it with 15.1.6.7. Anyway since the merging commits concern only you and to keep the commit feed clean I skipped them and merged your IO - Minor refactor only

**Comment by apobekiaris** [comment]
Can you please support also this case in your next update?
http://www.expandframework.com/forum/6-bugs/4639-iomodule-restore-deleted-objects-behavior.html#9275

**Comment by ErikWitkowski** [comment]
Sure! I think I can.

**Comment by ErikWitkowski** [comment]
Update: I don't have XAF 14.2 yet, and already used my trial up. My company curretly doesn't have a extimated time to buy a extension so I'm a little stuck on this for now.

**Pull request closed without merging**
