### PR TITLE
Ignore possible SecurityException from InterfaceBuilder.IsDevMachine

### PR DESCRIPTION
**Pull request by jhorv**
I was getting this SecurityException on a dev machine under full IIS using the ApplicationPoolIdentity

### CODE REVIEW

**Comment by jhorv** [comment]
Should mention, I was also getting this exception with 15.2 so maybe back-port.

**Comment by expand** [comment]
thanks for the fix I tried to fetch your repo however it downloads everything from the beginning and treats it like its not a fork but a different repo. I wonder what is the reason for this, maybe you forked my repo (apobekiaris) instead of the main (eXpand) repo

**Comment by jhorv** [comment]
Strange!  No, I forked from the main eXpand repo, 16.1 branch.  I didn't know you had a personal fork.

Looking at the [github page](https://github.com/expand/eXpand/pull/106) for this PR it all looks normal - fork of expand:16.1, 1 file changed.

**Comment by expand** [comment]
merged with 16.1.4.3

**Pull request closed without merging**
