### PR TITLE
remove the size limit (100 chars) from XpandRole.HiddenNavigationItems

### PR DESCRIPTION
**Pull request by jhorv**
; added VS2015 .vs/ folders to .gitignore

### CODE REVIEW

**Comment by apobekiaris** [comment]
I think you will agree that such small commits have not real value. So what I see is 2 commits I will use rebase to produce a user friendly commit line

1) remove the size limit (100 chars) from XpandRole.HiddenNavigationItems;  add VS2015 .vs/ folders to .gitignore
2)CodeRush plugin's "Xaf Models" list is empty if solution contains F# project	
http://www.expandframework.com/forum/6-bugs/4632-coderush-plugin-s-xaf-models-list-is-empty-if-solution-contains-f-project.html

**Comment by apobekiaris** [comment]
merged with 15.1.7.4

**Comment by jhorv** [comment]
Okay, I'll remember for next time.  I was trying to show the reasoning for each change since it wasn't one simple fix, but I suppose that's evident in the code itself.

**Comment by apobekiaris** [comment]
try to think what it will be needed when looking at files history. for example 
	move ToString() call out of loop
fix file/type name spelling, move ToString() call out of loop
there you translate c# in english and has no value. The questions comes to where you should commit those stuff. For such minor and unrelated probably commits i create a new commit "minor changes" and use rebase b4 push. anyway if you not sure feel free to ask for directions. I also use to rewrite history of my public personal 15.1 branch because i do not expect anyone to fork. I guess you can do the same on your develop branch

**Comment by apobekiaris** [comment]
last comment :) again using as example the "move ToString() call out of loop" commit. For the file history it is obvious that yes you "move ToString() call out of loop" however what not obvious is as to why u make that change. Again many times these changes are not interesting enough to justify the time needed to think for an appropriate message so they can be grouped to a "minor commit" commit message without fuirther explanation. Let me know if this strategy makes sense to you or if u have additions

**Comment by jhorv** [comment]
Makes sense, thanks for taking the time to explain!

**Pull request closed without merging**
